/*
    Rule Name: HEALTHBANE_Phishing_PDF
    Description: Detects weaponized PDF attachments generated by wkhtmltopdf 0.12.6 
                 and embedded with credential-harvesting parameters/portal links 
                 used in the HEALTHBANE campaign.
    Author: MedDefense
    Date: 2026-09-27
    Reference: Project 4x02 HEALTHBANE
    Threat Level: High
    Confidence: High
*/

rule HEALTHBANE_Phishing_PDF
{
    meta:
        author = "MedDefense CTI Team"
        description = "Detects HEALTHBANE campaign spear-phishing PDFs using wkhtmltopdf and credential harvesting paths."
        date = "2026-09-27"
        reference = "HEALTHBANE Campaign (Project 4x02)"
        threat_level = "High"
        confidence = "High"

    strings:
        // PDF file header magic bytes
        $pdf_header = { 25 50 44 46 }
        // Exact tooling fingerprint identified in campaign samples
        $tool_wkhtml = "wkhtmltopdf 0.12.6" ascii wide nocase
        // Campaign-specific URI paths and credential harvesting endpoints
        $path_verify = "/verify" ascii nocase
        $path_login  = "/portal/login" ascii nocase
        $path_pay    = "/invoices/pay" ascii nocase
        // Tracking and session parameter patterns used for victim token/ID capture
        $param_token = "token=" ascii nocase
        $param_id    = "id=" ascii nocase

    condition:
        // Must start with valid PDF magic header
        $pdf_header at 0
        and
        // Must contain the specific wkhtmltopdf generator producer string
        $tool_wkhtml
        and
        // Must contain at least one characteristic harvesting path/endpoint and one URL parameter/identifier
        (
            1 of ($path_verify, $path_login, $path_pay)
            and
            1 of ($param_token, $param_id)
        )
}

/*
    ============================================================================
    TEST RESULTS
    ============================================================================
    Command executed:
        $ yara 9-yara_phishing_pdf.yar samples/

    Output:
        HEALTHBANE_Phishing_PDF samples/phishing_sample.pdf
        HEALTHBANE_Phishing_PDF samples/healthbane_lure_02.pdf

    True Positives :
        - phishing_sample.pdf (Matched PDF header, wkhtmltopdf 0.12.6, /verify, and id/token parameters)
        - healthbane_lure_02.pdf (Matched PDF header, wkhtmltopdf 0.12.6, /invoices/pay, and id parameter)

    True Negatives :
        - clean_invoice.pdf (Generated by Adobe InDesign; lacks wkhtmltopdf and harvesting strings)
        - benign_invoice.pdf (Generated by Microsoft Print to PDF; lacks harvesting URIs)

    Conclusion:
        Rule demonstrates 100% precision across the test corpus with zero false positives.
*/