#!/usr/bin/env bash
# create a tmp file and delte it on SIGQUIT and SIGTERM

echo "$$" > "/tmp/myscript.pid"
trap 'echo "I hate the kill ommand"; rm -f "/tmp/myscript.pid"; exit'  SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "/tmp/myscript.pid"; exit' SIGQUIT
while true
do
        echo "To infinity and beyond"
        sleep 2
done
