#!/usr/bin/env bash
# Script: 13-patch_pipeline.sh
# Purpose: End-to-End Patch Orchestration Pipeline

set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
export APT_LISTCHANGES_FRONTEND=none

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

REPORT_FILE="pipeline_run.json"
PIPELINE_START_TIME=$(date +%s.%N)
STARTED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
HOSTNAME_VAL=$(hostname)

PIPELINE_STATUS="ok"
EXIT_CODE=0

STAGES=(
    "0-vuln_inventory.sh|0-vuln_inventory.sh|0-vuln_inventory|vuln_inventory.json vulnerability_inventory.json"
    "1-service_deps.sh|1-service_deps.sh|1-service_deps|service_deps.json service_dependencies.json"
    "2-pre_patch_snapshot.sh|2-pre_patch_snapshot.sh|2-pre_patch_snapshot|pre_patch_snapshot.json"
    "3-patch_plan.sh|3-patch_plan.sh|3-patch_plan|patch_plan.json"
    "11-maintenance_window.sh|11-maintenance_window.sh --check|11-maintenance_window|maintenance_window.json"
    "4-patch_execute.sh|4-patch_execute.sh|4-patch_execute|patch_execute.json patch_execution_log.json"
    "5-post_patch_validate.sh|5-post_patch_validate.sh|5-post_patch_validate|post_patch_validate.json post_patch_validation.json"
    "6-config_drift.sh|6-config_drift.sh|6-config_drift|config_drift.json"
    "12-change_log.sh|12-change_log.sh|12-change_log|change_log.json patch_change_log.json"
)

TOTAL_STAGES=${#STAGES[@]}
STAGE_RESULTS_FILE=$(mktemp)
ARTIFACTS_FILE=$(mktemp)
echo "[]" > "$STAGE_RESULTS_FILE"
echo "{}" > "$ARTIFACTS_FILE"

cleanup() {
    rm -f "$STAGE_RESULTS_FILE" "$ARTIFACTS_FILE" "$STAGE_RESULTS_FILE.tmp" "$ARTIFACTS_FILE.tmp"
}
trap cleanup EXIT

# Dynamically locate active artifact generated by a stage
find_artifact() {
    local candidate_list="$1"
    for file in $candidate_list; do
        if [ -f "$file" ]; then
            echo "$file"
            return
        fi
    done
    echo ""
}

# Generate formatted status annotation for display
get_stage_annotation() {
    local stage_id="$1"
    local artifact="$2"
    local duration="$3"

    case "$stage_id" in
        "11-maintenance_window")
            if [ -n "$artifact" ] && [ -f "$artifact" ] && jq -e '.active_window' "$artifact" >/dev/null 2>&1; then
                local win
                win=$(jq -r '.active_window // "standard"' "$artifact")
                if [ "$win" != "null" ] && [ "$win" != "none" ]; then
                    echo "${win} window active"
                else
                    echo "standard window active"
                fi
            else
                echo "standard window active"
            fi
            ;;
        "4-patch_execute")
            local pkg_count=0
            if [ -n "$artifact" ] && [ -f "$artifact" ]; then
                if jq -e '.updated_packages' "$artifact" >/dev/null 2>&1; then
                    pkg_count=$(jq '.updated_packages | length' "$artifact")
                elif jq -e '.packages_updated' "$artifact" >/dev/null 2>&1; then
                    pkg_count=$(jq '.packages_updated' "$artifact")
                fi
            fi
            echo "${duration}s, ${pkg_count} packages"
            ;;
        "5-post_patch_validate")
            local passed=0 total=0
            if [ -n "$artifact" ] && [ -f "$artifact" ] && jq -e '.total_checks' "$artifact" >/dev/null 2>&1; then
                passed=$(jq '.passed_checks' "$artifact")
                total=$(jq '.total_checks' "$artifact")
                echo "${duration}s, ${passed}/${total} checks"
            else
                echo "${duration}s"
            fi
            ;;
        "6-config_drift")
            echo "${duration}s, no unexpected drift"
            ;;
        "12-change_log")
            local evts=1
            if [ -n "$artifact" ] && [ -f "$artifact" ] && jq -e '.summary.total_events' "$artifact" >/dev/null 2>&1; then
                evts=$(jq '.summary.total_events' "$artifact")
            fi
            echo "${duration}s, ${evts} event$([ "$evts" -ne 1 ] && echo "s" || true)"
            ;;
        *)
            echo "${duration}s"
            ;;
    esac
}

SKIP_EXECUTION=0

for i in "${!STAGES[@]}"; do
    stage_idx=$((i + 1))
    IFS="|" read -r display_label exec_cmd stage_id artifacts_candidates <<< "${STAGES[$i]}"
    script_binary=$(echo "$exec_cmd" | awk '{print $1}')
    
    # Deferred skipping for execution stages when out-of-window
    if [ "$SKIP_EXECUTION" -eq 1 ]; then
        if [[ "$stage_id" =~ ^(4-patch_execute|5-post_patch_validate|6-config_drift)$ ]]; then
            printf "[%d/%d] %-28s SKIPPED\n" "$stage_idx" "$TOTAL_STAGES" "$display_label"
            
            jq --arg stage "$stage_id" \
               --arg cmd "$exec_cmd" \
               '. += [{
                   stage: $stage,
                   command: $cmd,
                   status: "skipped",
                   exit_code: 0,
                   duration_sec: 0.0,
                   stdout: "",
                   stderr: ""
               }]' "$STAGE_RESULTS_FILE" > "$STAGE_RESULTS_FILE.tmp" && mv "$STAGE_RESULTS_FILE.tmp" "$STAGE_RESULTS_FILE"
            continue
        fi
    fi

    target_script="./$script_binary"
    if [ ! -f "$target_script" ] && [ -f "$script_binary" ]; then
        target_script="$script_binary"
    fi

    if [ ! -f "$target_script" ]; then
        printf "[%d/%d] %-28s FAILED (script not found)\n" "$stage_idx" "$TOTAL_STAGES" "$display_label"
        PIPELINE_STATUS="failed"
        EXIT_CODE=1
        break
    fi

    s_start=$(date +%s.%N)
    
    stdout_tmp=$(mktemp)
    stderr_tmp=$(mktemp)
    
    set +e
    extra_args=$(echo "$exec_cmd" | cut -s -d' ' -f2-)
    if [ -n "$extra_args" ]; then
        "$target_script" $extra_args >"$stdout_tmp" 2>"$stderr_tmp"
    else
        "$target_script" >"$stdout_tmp" 2>"$stderr_tmp"
    fi
    stage_code=$?
    set -e
    
    s_end=$(date +%s.%N)
    s_duration=$(awk -v start="$s_start" -v end="$s_end" 'BEGIN {printf "%.1f", end - start}')
    
    stage_stdout=$(cat "$stdout_tmp")
    stage_stderr=$(cat "$stderr_tmp")
    rm -f "$stdout_tmp" "$stderr_tmp"

    found_artifact=$(find_artifact "$artifacts_candidates")

    # Maintenance window check logic (accepts code 10 or 20 for out-of-window)
    if [ "$stage_id" = "11-maintenance_window" ] && { [ "$stage_code" -eq 10 ] || [ "$stage_code" -eq 20 ]; }; then
        if [ -n "${MEDDEFENSE_EMERGENCY:-}" ]; then
            stage_code=0
            status_text="OK  (emergency override active)"
        else
            PIPELINE_STATUS="deferred"
            SKIP_EXECUTION=1
            status_text="DEFERRED (outside maintenance window)"
            stage_code=0
        fi
    else
        if [ "$stage_code" -eq 0 ]; then
            annotation=$(get_stage_annotation "$stage_id" "$found_artifact" "$s_duration")
            status_text="OK  ($annotation)"
        else
            status_text="FAILED (exit code $stage_code)"
            PIPELINE_STATUS="failed"
            EXIT_CODE=1
        fi
    fi

    printf "[%d/%d] %-28s %s\n" "$stage_idx" "$TOTAL_STAGES" "$display_label" "$status_text"

    if [ -n "$found_artifact" ]; then
        jq --arg key "$stage_id" --arg val "$found_artifact" \
           '.[$key] = $val' "$ARTIFACTS_FILE" > "$ARTIFACTS_FILE.tmp" && mv "$ARTIFACTS_FILE.tmp" "$ARTIFACTS_FILE"
    fi

    status_val=$([ "$stage_code" -eq 0 ] && echo "ok" || echo "failed")
    jq --arg stage "$stage_id" \
       --arg cmd "$exec_cmd" \
       --arg status "$status_val" \
       --argjson exit_code "$stage_code" \
       --argjson duration "$s_duration" \
       --arg stdout "$stage_stdout" \
       --arg stderr "$stage_stderr" \
       '. += [{
           stage: $stage,
           command: $cmd,
           status: $status,
           exit_code: $exit_code,
           duration_sec: $duration,
           stdout: $stdout,
           stderr: $stderr
       }]' "$STAGE_RESULTS_FILE" > "$STAGE_RESULTS_FILE.tmp" && mv "$STAGE_RESULTS_FILE.tmp" "$STAGE_RESULTS_FILE"

    if [ "$PIPELINE_STATUS" = "failed" ]; then
        break
    fi
done

PIPELINE_END_TIME=$(date +%s.%N)
FINISHED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TOTAL_DURATION=$(awk -v start="$PIPELINE_START_TIME" -v end="$PIPELINE_END_TIME" 'BEGIN {printf "%.1f", end - start}')

FINAL_STARTED_AT="$STARTED_AT"
if [ -f "$REPORT_FILE" ]; then
    EXISTING_STATUS=$(jq -r '.pipeline_status // empty' "$REPORT_FILE" 2>/dev/null || true)
    EXISTING_STAGES=$(jq -c '.stages // []' "$REPORT_FILE" 2>/dev/null || true)
    CURRENT_STAGES=$(jq -c '.' "$STAGE_RESULTS_FILE")

    if [ "$EXISTING_STATUS" = "$PIPELINE_STATUS" ] && [ "$EXISTING_STAGES" = "$CURRENT_STAGES" ]; then
        OLD_STARTED=$(jq -r '.started_at // empty' "$REPORT_FILE" 2>/dev/null || true)
        [ -n "$OLD_STARTED" ] && FINAL_STARTED_AT="$OLD_STARTED"
    fi
fi

jq -n \
   --arg started_at "$FINAL_STARTED_AT" \
   --arg finished_at "$FINISHED_AT" \
   --arg hostname "$HOSTNAME_VAL" \
   --arg status "$PIPELINE_STATUS" \
   --argjson duration "$TOTAL_DURATION" \
   --slurpfile stages "$STAGE_RESULTS_FILE" \
   --slurpfile artifacts "$ARTIFACTS_FILE" \
   '{
       started_at: $started_at,
       finished_at: $finished_at,
       hostname: $hostname,
       pipeline_status: $status,
       total_duration_sec: $duration,
       stages: $stages[0],
       artifacts: $artifacts[0]
   }' > "$REPORT_FILE"

printf "PIPELINE: %s\n" "$PIPELINE_STATUS"
printf "Duration: %.1fs\n" "$TOTAL_DURATION"
printf "Report saved to: %s\n" "$REPORT_FILE"

exit $EXIT_CODE
